### ISSUE TITLE
Add contacts to person edit

### ISSUE THREAD

**Issue by ndelvalle** [FindEarth/cms#26]

**Comment by ianaya89** [comment]
1. Add UI and layout to show contact data in edit mode.
2. Add logic to remove existing contact.
3. Add logic to add new contact.

**Comment by brianstanley** [comment]
![screen shot 2016-10-17 at 17 30 57](https://cloud.githubusercontent.com/assets/1711851/19454522/dc655ea8-948f-11e6-97dd-82e1d34ec8a0.png)

**Comment by brianstanley** [comment]
SOLVED PR #51

**Comment by ianaya89** [comment]
👍
