### ISSUE TITLE
Improve encontrados table fields

### ISSUE THREAD

**Issue by ndelvalle** [FindEarth/cms#44]
Remove fields:
* Ultima vez visto
* social icons

Add fields:
* Fecha en la que se encontro la persona

Maybe we should add how many days the person was missing before was found.

**Comment by ianaya89** [comment]
Sounds good. We need a shorter name for "Fecha en la que se encontro la persona" => "Encontrado" / "Fecha de Encontrado" / "Fecha de Encuentro" / "Fecha de Aparicion"

I like the idea of calculate how many days the person was missing. So we need to include another column calculating those days.

**Comment by ndelvalle** [comment]
I like `Encontrado`

**Comment by brianstanley** [comment]
We need to add an Encontrado date to the api in order to show the date that the person was found and for calculate how many days it was.

**Comment by ndelvalle** [comment]
Ok, assume we have that field as `foundAt`, and hardcode with a custom date until I implement it in the API 👍

**Comment by brianstanley** [comment]
👍

**Comment by brianstanley** [comment]
SOLVED PR #52

**Comment by ianaya89** [comment]
👍
