### ISSUE TITLE
Social share

### ISSUE THREAD

**Issue by ndelvalle** [FindEarth/cms#45]
Add social icons (Facebook, Instagram, Twitter) to person detail view. These should share the person profile. We don't have a public person details preview, but we should make one in the future for this functionality.

**Comment by ianaya89** [comment]
We probably need to register the application on Twitter, Instagram and Facebook before do that.
In the meantime crate a demo application in each social network wi will replace it later.

**Comment by brianstanley** [comment]
👍

**Comment by brianstanley** [comment]
SOLVED pr #54
