### ISSUE TITLE
Use a bar chart to represent lost by age

### ISSUE THREAD

**Issue by ndelvalle** [FindEarth/cms#48]
In the home page we have a pie chart to represent ppl lost by age.

<img width="579" alt="screen shot 2016-10-18 at 8 05 14 pm" src="https://cloud.githubusercontent.com/assets/6719053/19478909/8116c232-956e-11e6-9dd0-394bf2c6e815.png">

Lets change this to use a bar chart instead. So when we have 30 different ages the graph wont become a mess.

**Comment by ianaya89** [comment]
We are using [Chart.js](http://www.chartjs.org/) to work with charst.

**Comment by ianaya89** [comment]
:+1:
