### ISSUE TITLE
Create confirmation modal component.

### ISSUE THREAD

**Issue by ianaya89** [FindEarth/cms#61]
Refactor the modal used in `PersonRequestDetail.vue` and build new component with confirmation style to make it reusable.

**Comment by brianstanley** [comment]
RESOLVED PR #66

**Comment by ianaya89** [comment]
Both confirmation buttons must be right aligned:

<img width="654" alt="screen shot 2016-10-28 at 11 47 06 am" src="https://cloud.githubusercontent.com/assets/3258966/19810583/6f3104d6-9d04-11e6-99ff-79ed32bfc4c4.png">

**Comment by ianaya89** [comment]
LGTM
